#!/usr/bin/dh-exec
build/staging/bin/casparcg => usr/bin/casparcg-server-2.4
build/staging/casparcg.config => usr/share/casparcg-server-2.4/casparcg.config

debian/server.desktop => usr/share/applications/casparcg-server-2.4.desktop

debian/server-48x48.png   => usr/share/icons/hicolor/48x48/apps/casparcg-server-2.4.png
debian/server-128x128.png => usr/share/icons/hicolor/128x128/apps/casparcg-server-2.4.png
debian/server-256x256.png => usr/share/icons/hicolor/256x256/apps/casparcg-server-2.4.png
