name: Build Debian packages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-debian-stable:
    runs-on: ubuntu-latest
    container: debian:stable

    steps:
      - run: |
          apt-get -y update
          apt-get -y upgrade
          apt-get -y install build-essential git wget

      - uses: actions/checkout@v4

      - uses: robinraju/release-downloader@v1
        with:
          repository: dimitry-ishenko-casparcg/chromium-embedded-117
          latest: true
          fileName: libcef117{,-data,-dev}_*_amd64.deb

      - run: |
          git config --global --add safe.directory '*'
          apt-get -y install ./libcef117*_amd64.deb
          apt-get -y build-dep .
          dpkg-buildpackage --build=binary --no-sign

      - uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ../*.deb
          overwrite: true
